= Git session

Sharing some Git conveniences, `~/.bashrc` aliases, and scripts.

== Create rebase and squash convenience scripts

. Create the file `git-rebase-ocp-main` in `/usr/local/bin`:

.. `sudo atom /usr/local/bin/git-rebase-ocp-main`
+
[source,text]
----
#!/usr/bin/env bash

OPENSHIFT_MAIN_BRANCH="main"
OPENSHIFT_UPSTREAM_REMOTE="upstream"
OPENSHIFT_PERSONAL_REMOTE="origin"

set -e

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "ERROR: you must execute this script from the OpenShift Git repository." 1>&2
  exit 1
fi

git fetch --all
git stash

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

git checkout "$OPENSHIFT_MAIN_BRANCH"
git rebase "$OPENSHIFT_UPSTREAM_REMOTE/$OPENSHIFT_MAIN_BRANCH"
git push "$OPENSHIFT_PERSONAL_REMOTE" "$OPENSHIFT_MAIN_BRANCH"
git checkout "$CURRENT_BRANCH"

git stash pop

echo "Rebase successful." 1>&2

----

. Create the file `git-squash-commmits` in `/usr/local/bin`:

.. `sudo atom /usr/local/bin/git-squash-commits`
+
[source,text]
----
#!/usr/bin/env bash

OPENSHIFT_MAIN_BRANCH="main"
OPENSHIFT_PERSONAL_REMOTE="origin"

set -e

#Check if we're in a Git repository
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "ERROR: you must execute this script from the OpenShift Git repository." 1>&2
  exit 1
fi

#Get the current branch.
CURRENT_BRANCH="$(git branch --show-current)"

#Ensure you are not working off of the main branch.
if [ "$CURRENT_BRANCH" == "$OPENSHIFT_MAIN_BRANCH" ]; then
  echo "ERROR: you must not execute this script on the $OPENSHIFT_MAIN_BRANCH branch."
  exit 1
fi

#Pull with rebase in case there are remote/online edits to the PR.
git pull --rebase

#Get the base branch. This will allow you to specify a release branch if necessary.
read -p "Enter the name of the base branch for this branch? (e.g., main, enterprise-x.y): " BASE_BRANCH 

#Get the commit count using the base branch.
COMMIT_COUNT=$(git rev-list --count --no-merges $BASE_BRANCH..HEAD)

#If commit count is less than 2, exit. There's nothing to squash.
if [ $COMMIT_COUNT -lt 2 ]; then
  echo "Commit count is $COMMIT_COUNT. Nothing to squash."
  exit
fi

#If the commit count is suspiciously high, prompt the user for a commit count.
if [ $COMMIT_COUNT -gt 5 ]; then
  echo -e "Hmm...I'm counting $COMMIT_COUNT commits."
  echo "That seems a bit high."
  echo "Check your pull request commit count in the GitHub PR."
  read -p "How many commits do you want to squash? " COMMIT_COUNT
fi

#Check that a numerical value greater than zero was entered
test "$COMMIT_COUNT" -gt 0

#Prompt them on the commit count and branch name before commiting.
read -p "Do you want to squash $COMMIT_COUNT commits on branch $CURRENT_BRANCH to 1 commit? [y/N] " ANSWER

#Test to see if the user answers yes.
if [ $ANSWER == "Y" -o $ANSWER = "y" ];
then
  git reset --soft HEAD~$COMMIT_COUNT
  echo "Squashing $COMMIT_COUNT commits into 1 commit."
  read -p "Provide a commit message: " COMMIT_MESSAGE 
  git commit -m "$CURRENT_BRANCH: $COMMIT_MESSAGE"
  git push --force-with-lease
fi

echo "Squash successful." 1>&2

----

. Update permissions for the files you just created:
+
[source,terminal]
----
$ cd /usr/local/bin
----
+
[source,terminal]
----
$ sudo chmod +x git-rebase-ocp-main
----
+
[source,terminal]
----
$ sudo chmod +x git-squash-commits
----

cd to ocp docs folder, and try out the commands!

== Create some convenience aliases

. Open `~/.bashrc`, and add the following:
+
[source,text]
----
alias git-open-modified='atom $(git diff-tree HEAD HEAD~1 --no-commit-id --name-only -r)'
alias git-push-force='git push --force-with-lease'
alias git-commend-push-force='git commit --amend --reuse-message HEAD; git push --force-with-lease'
alias git-log-branch='git log --graph --abbrev-commit --decorate "$(git rev-parse --abbrev-ref HEAD)"'
----
+
[source,terminal]
----
$ source ~/.bashrc
----

== Git life savers

. Set up the git aware prompt!!! Details in the OCP user manual.

. *Every single time* you open a local feature branch that is based on the main branch:
+
[source,terminal]
----
$ git fetch --all
----
+
[source,terminal]
----
$ git rebase upstream/main
----
+
If you are working on an enterprise branch for release notes (replace `$VERSION` with the version you are working on):
+
[source,terminal]
----
$ git rebase upstream/enterprise-$VERSION
----

== Git some

=== Be aware of open files when switching branches!

When you switch branches, the files in your editor will remain open.
Be careful when closing them.
If you inadvertently save the file, you run the risk of accidentally adding the file to the wrong branch.

=== git checkout -b my-branch / git checkout my-branch

Be careful with the `-b` switch.
`-b` means: "Create a new branch based on the current branch and give it this name".
`git checkout my-branch` just means change to the named branch.

=== Oh no! I'm in the middle of an incorrect rebase!

[source,terminal]
----
$ git rebase --abort
----

=== Oh no! I've saved some files by accident but haven't committed, and want to put every back as it was in the most recent commit

[source,terminal]
----
$ git restore .
----

=== Oh no! I've totally ruined my feature branch and I want to return it to pristine condition before any commits

* Reset hard and then push:
+
[source,terminal]
----
$ git reset --hard upstream/main
----
+
[source,terminal]
----
$ git-push-force
----
+
For a branch based on (for example), enterprise-4.10:
+
[source,terminal]
----
$ git reset --hard upstream/enterprise-4.10
----
+
[source,terminal]
----
$ git-push-force
----

=== Oh no! I've pushed an incorrect commit to a PR by mistake!

* Get the commit ID for the bad commit from `git log` and revert the commit, then push your changes. A new revert commit is added to the PR.
+
[source,terminal]
----
$ git-log-branch
----
+
[source,terminal]
----
$ git revert 16bf19550b9f49bceec7fda7f765040357e0bcaf
----
+
[source,terminal]
----
$ git push
----

=== Oh no! I want to reset to the last good commit on my local branch

* Reset to last good commit:
+
[source,terminal]
----
$ git-log-branch
----
+
[source,terminal]
----
$ git reset 16bf19550b9f49bceec7fda7f765040357e0bcaf
----
+
[source,terminal]
----
$ git add .
----
+
[source,terminal]
----
$ git commit -m "reseting to last good commit"
----
+
[source,terminal]
----
$ git-push-force
----

=== Oh no! I created a PR against the wrong base:

link:https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request[Change the base!]
